package com.example.demo_1.ui.theme

import androidx.compose.ui.graphics.Color

val LavenderLightPrimary = Color(0xFF7A5AB0)
val LavenderLightOnPrimary = Color(0xFFFFFFFF)
val LavenderLightPrimaryContainer = Color(0xFFECDDFF)
val LavenderLightOnPrimaryContainer = Color(0xFF2C114E)
val LavenderLightSecondary = Color(0xFF6D5C85)
val LavenderLightOnSecondary = Color(0xFFFFFFFF)
val LavenderLightSecondaryContainer = Color(0xFFECDDFF)
val LavenderLightOnSecondaryContainer = Color(0xFF271A37)
val LavenderLightTertiary = Color(0xFF8C4F9A)
val LavenderLightOnTertiary = Color(0xFFFFFFFF)
val LavenderLightBackground = Color(0xFFF8F3FF)
val LavenderLightOnBackground = Color(0xFF1D1A24)
val LavenderLightSurface = Color(0xFFF8F3FF)
val LavenderLightOnSurface = Color(0xFF1D1A24)
val LavenderLightSurfaceVariant = Color(0xFFE8DFEE)
val LavenderLightOnSurfaceVariant = Color(0xFF4A4453)

val LavenderDarkPrimary = Color(0xFFD5BCFF)
val LavenderDarkOnPrimary = Color(0xFF422474)
val LavenderDarkPrimaryContainer = Color(0xFF5A3D8D)
val LavenderDarkOnPrimaryContainer = Color(0xFFECDDFF)
val LavenderDarkSecondary = Color(0xFFD1C0E9)
val LavenderDarkOnSecondary = Color(0xFF37294A)
val LavenderDarkSecondaryContainer = Color(0xFF4F3E62)
val LavenderDarkOnSecondaryContainer = Color(0xFFEDDEFF)
val LavenderDarkTertiary = Color(0xFFF0B2FF)
val LavenderDarkOnTertiary = Color(0xFF5A1A68)
val LavenderDarkBackground = Color(0xFF15121C)
val LavenderDarkOnBackground = Color(0xFFE8E0F2)
val LavenderDarkSurface = Color(0xFF15121C)
val LavenderDarkOnSurface = Color(0xFFE8E0F2)
val LavenderDarkSurfaceVariant = Color(0xFF4A4453)
val LavenderDarkOnSurfaceVariant = Color(0xFFCDC3D6)
